function GeneratedPost({ projects = [] }) {
  return (
    <article className="w-full pb-12 text-left text-base leading-8 md:text-lg">
      {projects.map((project, projectIndex) => (
        <div key={project.name}>
          <section
            className={`w-full pb-8 ${
              project.image
                ? "sm:grid sm:grid-cols-[minmax(0,2fr)_minmax(14rem,1fr)] sm:gap-8 lg:gap-12"
                : ""
            }`}
          >
            <div className="min-w-0 flex-1">
              <div className="mb-4 flex flex-wrap items-baseline gap-x-4 gap-y-1">
                <h2 className="text-xl font-semibold text-gray-900 md:text-2xl">
                  {project.url ? (
                    <a
                      href={project.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="transition-colors hover:text-blue-600 hover:underline"
                    >
                      {project.name}
                    </a>
                  ) : (
                    project.name
                  )}
                </h2>
                <div
                  className="flex items-center gap-3 text-sm font-semibold tabular-nums"
                  aria-label={`${project.changes.additions} lines added and ${project.changes.deletions} lines removed`}
                >
                  <span className="text-emerald-600">
                    +{project.changes.additions.toLocaleString()}
                  </span>
                  <span className="text-rose-600">
                    -{project.changes.deletions.toLocaleString()}
                  </span>
                </div>
              </div>
              <ul className="mb-4 list-disc space-y-2 pl-5 text-gray-800">
                {project.bullets.map((bullet, index) => (
                  <li key={`${project.name}-${index}`}>{bullet.text}</li>
                ))}
              </ul>
              <p className="text-gray-600">{project.summary.text}</p>
            </div>
            {project.image && (
              <>
                <div className="relative hidden min-h-0 sm:block">
                  <img
                    src={project.image}
                    alt={`${project.name} project update`}
                    loading="lazy"
                    className="absolute right-0 top-1/2 h-auto w-auto max-h-full max-w-full -translate-y-1/2 rounded-2xl object-contain shadow-xl ring-1 ring-black/5"
                  />
                </div>
                <img
                  src={project.image}
                  alt={`${project.name} project update`}
                  loading="lazy"
                  className="mt-6 block h-auto max-h-80 w-auto max-w-full rounded-2xl object-contain object-left shadow-xl ring-1 ring-black/5 sm:hidden"
                />
              </>
            )}
          </section>
          {projectIndex < projects.length - 1 && (
            <hr className="mb-10 w-full border-gray-200" />
          )}
        </div>
      ))}

      <p className="mt-10 text-center text-sm italic leading-6 text-gray-400">
        summaries are generated by AI from my github diffs. source code available in{" "}
        <a
          href="https://github.com/TehBandit/personal-website"
          target="_blank"
          rel="noreferrer"
          className="underline transition-colors hover:text-blue-500"
        >
          TehBandit/personal-website
        </a>
        .
      </p>
    </article>
  );
}

export default GeneratedPost;
